version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 500
      runas: root