spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(ttDKOvu2x6cYYiCFmalERHkAGFtDop8r)
    url: jdbc:mysql://localhost:3306/COVID_TRACKER
  application:
    name: Covid19IndiaTracker
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
logging:
  level:
    covidindiatracker.comtrackercovid19india: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
