spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: password
    url: jdbc:mysql://localhost:3306/COVID_TRACKER
  application:
    name: Covid19IndiaTracker
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    covidindiatracker.comtrackercovid19india: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
api:
  state-wise-url-json: https://api.covid19india.org/state_district_wise.json
  new-user-save-format: "/newuser?name=DUMMY&number=DUMMY&state=DUMMY&district=DUMMY Enter only 10 digit mobile number"
cloud:
  aws:
    region:
      auto: false
      static: us-east-1
    stack:
      auto: false
server:
  port: 39200
